name: CI/CD

on:
  push:
  pull_request:

jobs:
  ci-build-test:
    runs-on: ubuntu-latest
    container: joshkeegan/dotnet-build:6.0.100
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build
        run: make publish-all

      - name: Run Unit Tests
        working-directory: test/UnitTests
        run: make run
      
      - name: Upload artefacts
        uses: actions/upload-artifact@v3
        with:
          name: artefacts
          path: |
            artefacts
            sharedScripts
            src/StringSearch.Api.Host/Dockerfile
            src/StringSearch.Api.Host/out
            Makefile
        if: ${{ always() }}
  
  ci-docker:
    runs-on: ubuntu-latest
    needs: ci-build-test
    steps:
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artefacts
        uses: actions/download-artifact@v3
        with:
          name: artefacts
          path: .
      
      - name: Build Image
        run: |
          make \
            build-api-image \
            buildId="${{ github.run_number }}-${{ github.run_attempt }}" \
            commitHash="${GITHUB_SHA:0:8}"
      
      - name: Publish Image
        run: make publish-api-image